### ISSUE TITLE
Me help

### ISSUE THREAD

**Issue by redmasters** [eduardapalm/Rocket.Q_NWL#1]
Baixei seu código e vi que ele ta funcionado certinho. Queria te pedir ajuda pois o meu não está x__x.

Já verifiquei o código e ele me parece muito similar ao seu, não estou encontrando a falha. Não consigo marcar como lido ou excluir as mensagens.

Meu git: https://github.com/redmasters/roquetq

**Comment by eduardapalm** [comment]
oi, vou dar uma olhadinha aqui

Em dom, 27 de jun de 2021 10:47, Erasmo Jr. ***@***.***>
escreveu:

**Comment by eduardapalm** [comment]
Ainda tô mexendo aqui, pra ver se encontro a fonte do erro, qualquer progresso me avisa

**Comment by redmasters** [comment]
Obrigado @eduardapalm 🙏🏿

**Comment by eduardapalm** [comment]
Até agora nada kkkk eu tô ficando sem opções de tentativa.. mudei algumas coisinhas mas não ajudaram em nada

**Comment by redmasters** [comment]
Haha. Comparando com o teu código, mudei algumas coisas tb. Mas ainda segue
sem funcionar, não entendo kkk

**Comment by eduardapalm** [comment]
kkkk eu vou precisar parar agora, pq meu PC é compartilhado e outra pessoa vai usar.. mas mais tarde eu volto a tentar, se conseguir alguma coisa me avisa

**Comment by redmasters** [comment]
Bom dia @eduardapalm consegui arrumar. Os erros eram no meu main que nao mapeavam os botoes das actions e na room.ejs, onde a variavel do for each estava escrita no plural. Outra duvida, vc consegue deletar uma pergunta que ja foi lida?
